In [1]:
import bs4
from bs4 import BeautifulSoup
import requests
import re
import time
from datetime import datetime

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from selenium import webdriver
from mpl_toolkits.mplot3d import Axes3D

In [2]:
import os

print(os.getcwd())

c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\notebooks

In [3]:
#src\scraper.py
from car24.scraper import scrape_cars24_city

In [4]:
cities = {

    "Hyderabad":
    "https://www.cars24.com/buy-used-cars-hyderabad/?itm_source=Cars24Website&itm_medium=sticky_header",


    "Delhi":
    "https://www.cars24.com/buy-used-car?sort=P&storeCityId=2&pinId=110001",


    "Mumbai":
    "https://www.cars24.com/buy-used-car?sort=P&storeCityId=2378&pinId=400001",


    "Bangalore":
    "https://www.cars24.com/buy-used-car?sort=P&storeCityId=4709&pinId=560001",


    "Chennai":
    "https://www.cars24.com/buy-used-car?sort=P&storeCityId=5732&pinId=600001"
}

In [5]:
for city, url in cities.items():

    scrape_cars24_city(
        url=url,
        city_name=city
    )

Opening Hyderabad page...
Hyderabad | Scroll: 1 | Cars loaded: 100
Hyderabad | Scroll: 2 | Cars loaded: 140
Hyderabad | Scroll: 3 | Cars loaded: 160
Hyderabad | Scroll: 4 | Cars loaded: 160
Hyderabad | Scroll: 5 | Cars loaded: 160
Hyderabad | Scroll: 6 | Cars loaded: 160
Hyderabad | Scroll: 7 | Cars loaded: 160
Hyderabad | Scroll: 8 | Cars loaded: 160
No new cars loaded for 5 consecutive scrolls.

Hyderabad scraping completed.
Cars currently in DOM: 160
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Hyderabad.html

Opening Delhi page...
Delhi | Scroll: 1 | Cars loaded: 40
Delhi | Scroll: 2 | Cars loaded: 40
Delhi | Scroll: 3 | Cars loaded: 40
Delhi | Scroll: 4 | Cars loaded: 40
Delhi | Scroll: 5 | Cars loaded: 40
Delhi | Scroll: 6 | Cars loaded: 40
No new cars loaded for 5 consecutive scrolls.

Delhi scraping completed.
Cars currently in DOM: 40
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Delhi.html

Opening Mumbai page...
Mumbai | Scroll: 1 | Cars loaded: 120
Mumbai | Scroll: 2 | Cars loaded: 120
Mumbai | Scroll: 3 | Cars loaded: 120
Mumbai | Scroll: 4 | Cars loaded: 120
Mumbai | Scroll: 5 | Cars loaded: 120
Mumbai | Scroll: 6 | Cars loaded: 120
No new cars loaded for 5 consecutive scrolls.

Mumbai scraping completed.
Cars currently in DOM: 120
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Mumbai.html

Opening Bangalore page...
Bangalore | Scroll: 1 | Cars loaded: 20
Bangalore | Scroll: 2 | Cars loaded: 20
Bangalore | Scroll: 3 | Cars loaded: 20
Bangalore | Scroll: 4 | Cars loaded: 20
Bangalore | Scroll: 5 | Cars loaded: 20
Bangalore | Scroll: 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Bangalore scraping completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Bangalore.html

Opening Chennai page...
Chennai | Scroll: 1 | Cars loaded: 40
Chennai | Scroll: 2 | Cars loaded: 40
Chennai | Scroll: 3 | Cars loaded: 40
Chennai | Scroll: 4 | Cars loaded: 40
Chennai | Scroll: 5 | Cars loaded: 40
Chennai | Scroll: 6 | Cars loaded: 40
No new cars loaded for 5 consecutive scrolls.

Chennai scraping completed.
Cars currently in DOM: 40
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Chennai.html

In [5]:
for city, url in cities.items():

    for run_number in range(1, 5):

        scrape_cars24_city(
            url=url,
            city_name=city,
            run_number=run_number
        )

============================================================
Starting Hyderabad | Run 1
============================================================
Hyderabad | Run 1 | Scroll 1 | Cars loaded: 20
Hyderabad | Run 1 | Scroll 2 | Cars loaded: 20
Hyderabad | Run 1 | Scroll 3 | Cars loaded: 20
Hyderabad | Run 1 | Scroll 4 | Cars loaded: 20
Hyderabad | Run 1 | Scroll 5 | Cars loaded: 20
Hyderabad | Run 1 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Hyderabad Run 1 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Hyderabad_roll1.html

============================================================
Starting Hyderabad | Run 2
============================================================
Hyderabad | Run 2 | Scroll 1 | Cars loaded: 20
Hyderabad | Run 2 | Scroll 2 | Cars loaded: 20
Hyderabad | Run 2 | Scroll 3 | Cars loaded: 20
Hyderabad | Run 2 | Scroll 4 | Cars loaded: 20
Hyderabad | Run 2 | Scroll 5 | Cars loaded: 20
Hyderabad | Run 2 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Hyderabad Run 2 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Hyderabad_roll2.html

============================================================
Starting Hyderabad | Run 3
============================================================
Hyderabad | Run 3 | Scroll 1 | Cars loaded: 20
Hyderabad | Run 3 | Scroll 2 | Cars loaded: 20
Hyderabad | Run 3 | Scroll 3 | Cars loaded: 20
Hyderabad | Run 3 | Scroll 4 | Cars loaded: 20
Hyderabad | Run 3 | Scroll 5 | Cars loaded: 20
Hyderabad | Run 3 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Hyderabad Run 3 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Hyderabad_roll3.html

============================================================
Starting Hyderabad | Run 4
============================================================
Hyderabad | Run 4 | Scroll 1 | Cars loaded: 20
Hyderabad | Run 4 | Scroll 2 | Cars loaded: 20
Hyderabad | Run 4 | Scroll 3 | Cars loaded: 20
Hyderabad | Run 4 | Scroll 4 | Cars loaded: 20
Hyderabad | Run 4 | Scroll 5 | Cars loaded: 20
Hyderabad | Run 4 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Hyderabad Run 4 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Hyderabad_roll4.html

============================================================
Starting Delhi | Run 1
============================================================
Delhi | Run 1 | Scroll 1 | Cars loaded: 40
Delhi | Run 1 | Scroll 2 | Cars loaded: 40
Delhi | Run 1 | Scroll 3 | Cars loaded: 40
Delhi | Run 1 | Scroll 4 | Cars loaded: 40
Delhi | Run 1 | Scroll 5 | Cars loaded: 40
Delhi | Run 1 | Scroll 6 | Cars loaded: 40
No new cars loaded for 5 consecutive scrolls.

Delhi Run 1 completed.
Cars currently in DOM: 40
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Delhi_roll1.html

============================================================
Starting Delhi | Run 2
============================================================
Delhi | Run 2 | Scroll 1 | Cars loaded: 40
Delhi | Run 2 | Scroll 2 | Cars loaded: 40
Delhi | Run 2 | Scroll 3 | Cars loaded: 40
Delhi | Run 2 | Scroll 4 | Cars loaded: 40
Delhi | Run 2 | Scroll 5 | Cars loaded: 40
Delhi | Run 2 | Scroll 6 | Cars loaded: 40
No new cars loaded for 5 consecutive scrolls.

Delhi Run 2 completed.
Cars currently in DOM: 40
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Delhi_roll2.html

============================================================
Starting Delhi | Run 3
============================================================
Delhi | Run 3 | Scroll 1 | Cars loaded: 40
Delhi | Run 3 | Scroll 2 | Cars loaded: 40
Delhi | Run 3 | Scroll 3 | Cars loaded: 40
Delhi | Run 3 | Scroll 4 | Cars loaded: 40
Delhi | Run 3 | Scroll 5 | Cars loaded: 40
Delhi | Run 3 | Scroll 6 | Cars loaded: 40
No new cars loaded for 5 consecutive scrolls.

Delhi Run 3 completed.
Cars currently in DOM: 40
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Delhi_roll3.html

============================================================
Starting Delhi | Run 4
============================================================
Delhi | Run 4 | Scroll 1 | Cars loaded: 40
Delhi | Run 4 | Scroll 2 | Cars loaded: 40
Delhi | Run 4 | Scroll 3 | Cars loaded: 40
Delhi | Run 4 | Scroll 4 | Cars loaded: 40
Delhi | Run 4 | Scroll 5 | Cars loaded: 40
Delhi | Run 4 | Scroll 6 | Cars loaded: 40
No new cars loaded for 5 consecutive scrolls.

Delhi Run 4 completed.
Cars currently in DOM: 40
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Delhi_roll4.html

============================================================
Starting Mumbai | Run 1
============================================================
Mumbai | Run 1 | Scroll 1 | Cars loaded: 20
Mumbai | Run 1 | Scroll 2 | Cars loaded: 20
Mumbai | Run 1 | Scroll 3 | Cars loaded: 20
Mumbai | Run 1 | Scroll 4 | Cars loaded: 20
Mumbai | Run 1 | Scroll 5 | Cars loaded: 20
Mumbai | Run 1 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Mumbai Run 1 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Mumbai_roll1.html

============================================================
Starting Mumbai | Run 2
============================================================
Mumbai | Run 2 | Scroll 1 | Cars loaded: 20
Mumbai | Run 2 | Scroll 2 | Cars loaded: 20
Mumbai | Run 2 | Scroll 3 | Cars loaded: 20
Mumbai | Run 2 | Scroll 4 | Cars loaded: 20
Mumbai | Run 2 | Scroll 5 | Cars loaded: 20
Mumbai | Run 2 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Mumbai Run 2 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Mumbai_roll2.html

============================================================
Starting Mumbai | Run 3
============================================================
Mumbai | Run 3 | Scroll 1 | Cars loaded: 20
Mumbai | Run 3 | Scroll 2 | Cars loaded: 20
Mumbai | Run 3 | Scroll 3 | Cars loaded: 20
Mumbai | Run 3 | Scroll 4 | Cars loaded: 20
Mumbai | Run 3 | Scroll 5 | Cars loaded: 20
Mumbai | Run 3 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Mumbai Run 3 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Mumbai_roll3.html

============================================================
Starting Mumbai | Run 4
============================================================
Mumbai | Run 4 | Scroll 1 | Cars loaded: 20
Mumbai | Run 4 | Scroll 2 | Cars loaded: 20
Mumbai | Run 4 | Scroll 3 | Cars loaded: 20
Mumbai | Run 4 | Scroll 4 | Cars loaded: 20
Mumbai | Run 4 | Scroll 5 | Cars loaded: 20
Mumbai | Run 4 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Mumbai Run 4 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Mumbai_roll4.html

============================================================
Starting Bangalore | Run 1
============================================================
Bangalore | Run 1 | Scroll 1 | Cars loaded: 20
Bangalore | Run 1 | Scroll 2 | Cars loaded: 20
Bangalore | Run 1 | Scroll 3 | Cars loaded: 20
Bangalore | Run 1 | Scroll 4 | Cars loaded: 20
Bangalore | Run 1 | Scroll 5 | Cars loaded: 20
Bangalore | Run 1 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Bangalore Run 1 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Bangalore_roll1.html

============================================================
Starting Bangalore | Run 2
============================================================
Bangalore | Run 2 | Scroll 1 | Cars loaded: 20
Bangalore | Run 2 | Scroll 2 | Cars loaded: 20
Bangalore | Run 2 | Scroll 3 | Cars loaded: 20
Bangalore | Run 2 | Scroll 4 | Cars loaded: 20
Bangalore | Run 2 | Scroll 5 | Cars loaded: 20
Bangalore | Run 2 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Bangalore Run 2 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Bangalore_roll2.html

============================================================
Starting Bangalore | Run 3
============================================================
Bangalore | Run 3 | Scroll 1 | Cars loaded: 20
Bangalore | Run 3 | Scroll 2 | Cars loaded: 20
Bangalore | Run 3 | Scroll 3 | Cars loaded: 20
Bangalore | Run 3 | Scroll 4 | Cars loaded: 20
Bangalore | Run 3 | Scroll 5 | Cars loaded: 20
Bangalore | Run 3 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Bangalore Run 3 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Bangalore_roll3.html

============================================================
Starting Bangalore | Run 4
============================================================
Bangalore | Run 4 | Scroll 1 | Cars loaded: 20
Bangalore | Run 4 | Scroll 2 | Cars loaded: 20
Bangalore | Run 4 | Scroll 3 | Cars loaded: 20
Bangalore | Run 4 | Scroll 4 | Cars loaded: 20
Bangalore | Run 4 | Scroll 5 | Cars loaded: 20
Bangalore | Run 4 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Bangalore Run 4 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Bangalore_roll4.html

============================================================
Starting Chennai | Run 1
============================================================
Chennai | Run 1 | Scroll 1 | Cars loaded: 20
Chennai | Run 1 | Scroll 2 | Cars loaded: 20
Chennai | Run 1 | Scroll 3 | Cars loaded: 20
Chennai | Run 1 | Scroll 4 | Cars loaded: 20
Chennai | Run 1 | Scroll 5 | Cars loaded: 20
Chennai | Run 1 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Chennai Run 1 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Chennai_roll1.html

============================================================
Starting Chennai | Run 2
============================================================
Chennai | Run 2 | Scroll 1 | Cars loaded: 20
Chennai | Run 2 | Scroll 2 | Cars loaded: 20
Chennai | Run 2 | Scroll 3 | Cars loaded: 20
Chennai | Run 2 | Scroll 4 | Cars loaded: 20
Chennai | Run 2 | Scroll 5 | Cars loaded: 20
Chennai | Run 2 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Chennai Run 2 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Chennai_roll2.html

============================================================
Starting Chennai | Run 3
============================================================
Chennai | Run 3 | Scroll 1 | Cars loaded: 20
Chennai | Run 3 | Scroll 2 | Cars loaded: 20
Chennai | Run 3 | Scroll 3 | Cars loaded: 20
Chennai | Run 3 | Scroll 4 | Cars loaded: 20
Chennai | Run 3 | Scroll 5 | Cars loaded: 20
Chennai | Run 3 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Chennai Run 3 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Chennai_roll3.html

============================================================
Starting Chennai | Run 4
============================================================
Chennai | Run 4 | Scroll 1 | Cars loaded: 20
Chennai | Run 4 | Scroll 2 | Cars loaded: 20
Chennai | Run 4 | Scroll 3 | Cars loaded: 20
Chennai | Run 4 | Scroll 4 | Cars loaded: 20
Chennai | Run 4 | Scroll 5 | Cars loaded: 20
Chennai | Run 4 | Scroll 6 | Cars loaded: 20
No new cars loaded for 5 consecutive scrolls.

Chennai Run 4 completed.
Cars currently in DOM: 20
HTML saved at:
c:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Chennai_roll4.html

In [2]:
data_H = open(r'C:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Hyderabad.html','r')
soup_H = BeautifulSoup(data_H, 'html.parser')

In [3]:
data_D = open(r'C:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Delhi.html','r',encoding='utf-8')
soup_D = BeautifulSoup(data_D, 'html.parser')

In [4]:
data_M = open(r'C:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Mumbai.html','r',encoding='utf-8')
soup_M = BeautifulSoup(data_M, 'html.parser')

In [5]:
data_B = open(r'C:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Bangalore.html','r',encoding='utf-8')
soup_B = BeautifulSoup(data_B, 'html.parser')

In [6]:
data_C = open(r'C:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\raw\cars24_Chennai.html', 'r', encoding='utf-8')
soup_C = BeautifulSoup(data_C, 'html.parser')

In [18]:
main_div = 'col-4'
sub_div = '_1l4fi'
subsub_div = {'name':'_1jpRU','price':'_7udZZ','emi':'_2HFRN' , 'features':'bVR0c'}

In [19]:
print(len(soup_H.find_all("div")))

1430

In [20]:
print(len(soup_H.find_all("div", {"class": main_div})))

0

#### Creating empty list to store all the details

In [14]:
name_H, name_D, name_M, name_B, name_C = [],[],[],[],[]
price_H, price_D, price_M, price_B, price_C = [],[],[],[],[]
emi_H, emi_D, emi_M, emi_B, emi_C = [],[],[],[],[]
features_H, features_D, features_M, features_B, features_C = [],[],[],[],[]
city_H, city_D, city_M, city_B, city_C = [],[],[],[],[]

In [15]:
name = []
price = []
emi = []
features = []
city = []

In [16]:
soups = [soup_H, soup_D, soup_M, soup_B, soup_C]

In [9]:
from car24.scraper import extract_car_data

In [8]:
# only for hydrabad
df_H = extract_car_data(
    soup_H,
    "Hyderabad"
)

Hyderabad: 80 car cards found

In [9]:
df_H.head()

,year,name,variant,price,emi,driven_km,fuel,transmission,registration,location,city
0,2023,Nissan MAGNITE,XL,517000.0,9135.0,41774,Petrol,Manual,TS-36,"Kompally, Hyderabad",Hyderabad
1,2022,Maruti Swift,VXI,519000.0,9156.0,40355,Petrol,Manual,TS-15,"Upperpally, Attapur, Hyderabad",Hyderabad
2,2020,Renault Kwid,CLIMBER 1.0 (O),282000.0,4982.0,66791,Petrol,Manual,TS-15,"Kompally, Hyderabad",Hyderabad
3,2023,Maruti Swift,ZXI,593000.0,10470.0,62871,Petrol,Manual,TS-07,"Upperpally, Attapur, Hyderabad",Hyderabad
4,2019,KIA SELTOS,HTK 1.5 PETROL,661000.0,11665.0,70038,Petrol,Manual,TS-10,"Upperpally, Attapur, Hyderabad",Hyderabad

In [7]:
soups = {
    "Hyderabad": soup_H,
    "Delhi": soup_D,
    "Mumbai": soup_M,
    "Bangalore": soup_B,
    "Chennai": soup_C
}

In [10]:
dfs = []

for city, soup in soups.items():

    df_city = extract_car_data(
        soup,
        city
    )

    dfs.append(df_city)

df = pd.concat(
    dfs,
    ignore_index=True
)

Hyderabad: 160 car cards found
Delhi: 40 car cards found
Mumbai: 120 car cards found
Bangalore: 20 car cards found
Chennai: 40 car cards found

In [11]:
len(df['name'])

380

In [10]:
soups = {
    'Hyderabad': soup_H,
    'Delhi': soup_D,
    'Mumbai': soup_M,
    'Bangalore': soup_B,
    'Chennai': soup_C
}

In [11]:
dataframes = []

for city, soup in soups.items():
    df_city = extract_car_data(soup, city)
    dataframes.append(df_city)

df = pd.concat(dataframes, ignore_index=True)

In [12]:
df.head()

,year,name,variant,price,emi,driven_km,fuel,transmission,registration,location,city
0,2023,Nissan MAGNITE,XL,517000.0,9135.0,41774,Petrol,Manual,TS-36,"Kompally, Hyderabad",Hyderabad
1,2022,Maruti Swift,VXI,519000.0,9156.0,40355,Petrol,Manual,TS-15,"Upperpally, Attapur, Hyderabad",Hyderabad
2,2020,Renault Kwid,CLIMBER 1.0 (O),282000.0,4982.0,66791,Petrol,Manual,TS-15,"Kompally, Hyderabad",Hyderabad
3,2023,Maruti Swift,ZXI,593000.0,10470.0,62871,Petrol,Manual,TS-07,"Upperpally, Attapur, Hyderabad",Hyderabad
4,2019,KIA SELTOS,HTK 1.5 PETROL,661000.0,11665.0,70038,Petrol,Manual,TS-10,"Upperpally, Attapur, Hyderabad",Hyderabad

In [15]:
df.to_csv(r"C:\Users\DELL\Desktop\room208\Ankit\Car_prize_forcasting\data\csvs\Cars24.csv")

In [14]:
print("Total divs:", len(soup_H.find_all("div")))

Total divs: 1430

In [15]:
print("Title:", soup_H.title.get_text(strip=True) if soup_H.title else None)

Title: Used Cars in Hyderabad - 2309 Second Hand Cars | Cars24

In [16]:
print(soup_H.get_text(" ", strip=True)[:2000])

Used Cars in Hyderabad - 2309 Second Hand Cars | Cars24 Hyderabad Buy used car Buy Used Cars in Hyderabad Change city Browse by Model Browse by Make Browse by Price Browse by Body Type Browse by Fuel Type Browse by Transmission Browse by City Browse by Model Used Hyundai i10 Cars in Hyderabad Used Hyundai i20 Cars in Hyderabad Used Maruti Swift Cars in Hyderabad Used Tata NEXON Cars in Hyderabad Used Maruti Baleno Cars in Hyderabad Used Renault Kwid Cars in Hyderabad Used Maruti Wagon R Cars in Hyderabad Used Honda City Cars in Hyderabad Used Maruti Dzire Cars in Hyderabad Used KIA SELTOS Cars in Hyderabad Buy cars online Browse by Make Buy cars online Browse by Price Used Cars Under 2 lakhs in Hyderabad Used Cars Under 3 lakhs in Hyderabad Used Cars Under 4 lakhs in Hyderabad Used Cars Under 5 lakhs in Hyderabad Used Cars Under 7 lakhs in Hyderabad Used Cars Under 8 lakhs in Hyderabad Used Cars Under 10 lakhs in Hyderabad Used Cars Under 12 lakhs in Hyderabad Used Cars Under 15 lakhs in Hyderabad Used Cars Under 20 lakhs in Hyderabad Buy cars online Browse by Body Type Hatchback SUV Sedan Buy cars online Browse by Fuel Type Petrol Diesel CNG Electric Hybrid Buy cars online Browse by Transmission Manual Automatic Buy cars online Browse by City Used Cars in Delhi NCR Used Cars in Bangalore Used Cars in New Delhi Used Cars in Mumbai Used Cars in Hyderabad Used Cars in Pune Used Cars in Ahmedabad Used Cars in Gurgaon Used Cars in Chennai Used Cars in Noida Used Cars in Kolkata Used Cars in Ghaziabad Used Cars in Lucknow Used Cars in Jaipur Used Cars in Surat Buy cars online Sell car Sell car Used car valuation Sell car in Delhi Sell car in Mumbai Sell car in Bangalore Sell car in Hyderabad Sell car in Ahmedabad Sell car in Gurgaon Sell car in Chennai Sell car in Pune Sell car in Noida Sell car in Ghaziabad Sell car in Lucknow Sell car in Jaipur Sell car in Kolkata Sell car in Kochi Sell car in Indore Car finance Used car loan Loan against car Personal loan Credit cards

In [17]:
for div in soup_H.find_all("div")[:50]:
    classes = div.get("class")
    if classes:
        print(classes)

['styles_locationNudge__SS0H0']
['container', 'styles_headerContainer__zDx_u']
['styles_leftNavWrapper__opqQD']
['styles_logoWrapper___J4WM']
['styles_dropdownWrapper___CFX_']
['styles_cityName__VUTON']
['styles_mainMenu__Zlk7_']
['styles_hoverText__rB5MU']
['styles_loginDropdownfirst__PgxUq', 'styles_carFind__0Zs0j']
['styles_headerDropDownContainer__viHRK']
['sc-dkKxlL', 'gCQDqR']
['sc-gkSfoi', 'bjjtXv']
['sc-fmPOXF', 'jmGHgL']
['sc-eYqcxM', 'gZbBPg']
['sc-iFoMEL', 'GEwwd']
['sc-iFoMEL', 'glmCET']
['sc-iFoMEL', 'glmCET']
['sc-iFoMEL', 'glmCET']
['sc-iFoMEL', 'glmCET']
['sc-iFoMEL', 'glmCET']
['sc-iFoMEL', 'glmCET']
['sc-kSGOQT', 'bttQry']
['sc-jsTgWx', 'eTzcaI']
['sc-dvEHMo', 'ezjRSN']
['sc-kiPvrT', 'cEaFDD']
['sc-knEsKJ', 'vqeOu']
['sc-cxdZMk', 'bYWPcs']
['sc-kiPvrT', 'cEaFDD']
['sc-knEsKJ', 'vqeOu']
['sc-cxdZMk', 'bYWPcs']
['sc-kiPvrT', 'cEaFDD']
['sc-knEsKJ', 'vqeOu']
['sc-cxdZMk', 'bYWPcs']
['sc-kiPvrT', 'cEaFDD']
['sc-knEsKJ', 'vqeOu']
['sc-cxdZMk', 'bYWPcs']
['sc-kiPvrT', 'cEaFDD']
['sc-knEsKJ', 'vqeOu']
['sc-cxdZMk', 'bYWPcs']
['sc-kiPvrT', 'cEaFDD']
['sc-knEsKJ', 'vqeOu']
['sc-cxdZMk', 'bYWPcs']
['sc-kiPvrT', 'cEaFDD']
['sc-knEsKJ', 'vqeOu']
['sc-cxdZMk', 'bYWPcs']
['sc-kiPvrT', 'cEaFDD']
['sc-knEsKJ', 'vqeOu']
['sc-cxdZMk', 'bYWPcs']
['sc-kiPvrT', 'cEaFDD']
['sc-knEsKJ', 'vqeOu']

In [21]:
for text in soup_H.find_all(string=lambda x: x and "Hyundai" in x)[:10]:
    print("TEXT:", text.strip())
    print("PARENT:", text.parent.name)
    print("PARENT CLASS:", text.parent.get("class"))
    print("-" * 50)

TEXT: Used Hyundai i10 Cars in Hyderabad
PARENT: p
PARENT CLASS: ['sc-csuSiJ', 'jJLDTq']
--------------------------------------------------
TEXT: Used Hyundai i20 Cars in Hyderabad
PARENT: p
PARENT CLASS: ['sc-csuSiJ', 'jJLDTq']
--------------------------------------------------
TEXT: Hyundai Creta
PARENT: p
PARENT CLASS: ['sc-csuSiJ', 'jJLDTq']
--------------------------------------------------
TEXT: Hyundai
PARENT: p
PARENT CLASS: ['sc-csuSiJ', 'bHTJoO']
--------------------------------------------------
TEXT: Hyundai
PARENT: a
PARENT CLASS: None
--------------------------------------------------
TEXT: Used Hyundai Creta cars
PARENT: a
PARENT CLASS: None
--------------------------------------------------
TEXT: Used Hyundai Grand i10 cars
PARENT: a
PARENT CLASS: None
--------------------------------------------------
TEXT: Used Hyundai Verna cars
PARENT: a
PARENT CLASS: None
--------------------------------------------------
TEXT: Used Hyundai Elite i20 cars
PARENT: a
PARENT CLASS: None
--------------------------------------------------
TEXT: Used Hyundai VENUE cars
PARENT: a
PARENT CLASS: None
--------------------------------------------------

In [22]:
for text in soup_H.find_all(string=lambda x: x and "₹" in x)[:10]:
    print("TEXT:", text.strip())
    print("PARENT:", text.parent.name)
    print("PARENT CLASS:", text.parent.get("class"))
    print("-" * 50)

In [23]:
for keyword in ["₹", "km", "Petrol", "Diesel", "Manual", "Automatic"]:
    print(keyword, len(soup_H.find_all(string=lambda x: x and keyword in x)))

₹ 0
km 24
Petrol 28
Diesel 10
Manual 26
Automatic 7

In [24]:
creta = soup_H.find(
    string=lambda x: x and x.strip() == "Hyundai Creta"
)

print("TEXT:", creta)
print("PARENT:", creta.parent)

TEXT: Hyundai Creta
PARENT: <p class="sc-csuSiJ jJLDTq">Hyundai Creta</p>

In [25]:
parent = creta.parent

for level in range(6):
    print("\nLEVEL:", level)
    print("TAG:", parent.name)
    print("CLASS:", parent.get("class"))
    print("TEXT:", parent.get_text(" | ", strip=True)[:1000])
    print("-" * 80)

    parent = parent.parent

LEVEL: 0
TAG: p
CLASS: ['sc-csuSiJ', 'jJLDTq']
TEXT: Hyundai Creta
--------------------------------------------------------------------------------

LEVEL: 1
TAG: div
CLASS: ['sc-bhNKFj', 'ia-Dref']
TEXT: Hyundai Creta
--------------------------------------------------------------------------------

LEVEL: 2
TAG: div
CLASS: ['sc-dubCtS', 'gWmpsm']
TEXT: Hyundai Creta
--------------------------------------------------------------------------------

LEVEL: 3
TAG: a
CLASS: ['sc-fHSyaj', 'isyUYd']
TEXT: Hyundai Creta
--------------------------------------------------------------------------------

LEVEL: 4
TAG: div
CLASS: ['sc-gJqSRp', 'iXyUnt']
TEXT: Hyundai Creta | Mahindra Thar | Tata Nexon | Tata Punch | Maruti Swift | Kia Seltos
--------------------------------------------------------------------------------

LEVEL: 5
TAG: div
CLASS: ['sc-evzXkY', 'AJUHq']
TEXT: Hyundai Creta | Mahindra Thar | Tata Nexon | Tata Punch | Maruti Swift | Kia Seltos
--------------------------------------------------------------------------------

In [26]:
for keyword in ["Lakh", "Lakhs", "Rs", "lakh", "Price"]:
    count = len(
        soup_H.find_all(
            string=lambda x: x and keyword in x
        )
    )
    print(keyword, count)

Lakh 6
Lakhs 5
Rs 1
lakh 62
Price 9

In [27]:
petrol = soup_H.find(
    string=lambda x: x and x.strip() == "Petrol"
)

print("TEXT:", petrol)
print("PARENT:", petrol.parent)

parent = petrol.parent

for level in range(6):
    print("\nLEVEL:", level)
    print("TAG:", parent.name)
    print("CLASS:", parent.get("class"))
    print("TEXT:", parent.get_text(" | ", strip=True)[:1000])
    print("-" * 80)

    parent = parent.parent

TEXT: Petrol
PARENT: <p class="sc-csuSiJ jJLDTq">Petrol</p>

LEVEL: 0
TAG: p
CLASS: ['sc-csuSiJ', 'jJLDTq']
TEXT: Petrol
--------------------------------------------------------------------------------

LEVEL: 1
TAG: span
CLASS: ['sc-kMjNwB', 'caXMnc']
TEXT: Petrol
--------------------------------------------------------------------------------

LEVEL: 2
TAG: a
CLASS: ['sc-bYMpWq', 'dWepEO']
TEXT: Petrol
--------------------------------------------------------------------------------

LEVEL: 3
TAG: div
CLASS: ['sc-gikAfI', 'gCvxam']
TEXT: Petrol
--------------------------------------------------------------------------------

LEVEL: 4
TAG: div
CLASS: ['sc-iJbNxx', 'kjopQD']
TEXT: Petrol
--------------------------------------------------------------------------------

LEVEL: 5
TAG: div
CLASS: ['sc-cLNono', 'gLZnUN']
TEXT: Petrol | Diesel | CNG | Electric | Hybrid
--------------------------------------------------------------------------------

In [28]:
cards = soup_H.find_all(
    "div",
    class_=["sc-kiPvrT", "cEaFDD"]
)

print("Number of elements:", len(cards))

Number of elements: 55

In [29]:
cards = soup_H.select("div.sc-kiPvrT.cEaFDD")

print("Number of elements:", len(cards))

Number of elements: 55

In [30]:
for i, card in enumerate(cards[:3]):
    print("\n================ CARD", i, "================")
    print(card.get_text(" | ", strip=True))

================ CARD 0 ================
Used Hyundai i10 Cars in Hyderabad

================ CARD 1 ================
Used Hyundai i20 Cars in Hyderabad

================ CARD 2 ================
Used Maruti Swift Cars in Hyderabad

In [31]:
print(cards[0].prettify()[:5000])

<div class="sc-kiPvrT cEaFDD">
 <div class="sc-knEsKJ vqeOu">
  <p class="sc-csuSiJ jJLDTq">
   Used Hyundai i10 Cars in Hyderabad
  </p>
 </div>
 <div class="sc-cxdZMk bYWPcs">
  <svg class="sc-dkrFOf Ixvjl" style="transform:rotate(315deg)" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
   <path d="M17.317 10.442l-5.625 5.625a.625.625 0 11-.884-.884l4.558-4.558H3.125a.625.625 0 110-1.25h12.241l-4.558-4.558a.625.625 0 01.884-.884l5.625 5.625a.626.626 0 010 .884z" fill="#EF6E0B">
   </path>
  </svg>
 </div>
</div>

In [33]:
km_elements = soup_H.find_all(
    string=lambda x: x and "km" in x.lower()
)

print("Number:", len(km_elements))

for x in km_elements[:10]:
    print("\nTEXT:", repr(x.strip()))
    print("PARENT:", x.parent)
    print("PARENT CLASS:", x.parent.get("class"))

Number: 26

TEXT: 'Kms Driven'
PARENT: <p class="sc-bcXHqh cBmhVP">Kms Driven</p>
PARENT CLASS: ['sc-bcXHqh', 'cBmhVP']

TEXT: '28,750 km'
PARENT: <p class="sc-iBYQkw ffCutd" id="">28,750 km</p>
PARENT CLASS: ['sc-iBYQkw', 'ffCutd']

TEXT: '63,925 km'
PARENT: <p class="sc-iBYQkw ffCutd" id="">63,925 km</p>
PARENT CLASS: ['sc-iBYQkw', 'ffCutd']

TEXT: '38,495 km'
PARENT: <p class="sc-iBYQkw ffCutd" id="">38,495 km</p>
PARENT CLASS: ['sc-iBYQkw', 'ffCutd']

TEXT: '62,584 km'
PARENT: <p class="sc-iBYQkw ffCutd" id="">62,584 km</p>
PARENT CLASS: ['sc-iBYQkw', 'ffCutd']

TEXT: '46,197 km'
PARENT: <p class="sc-iBYQkw ffCutd" id="">46,197 km</p>
PARENT CLASS: ['sc-iBYQkw', 'ffCutd']

TEXT: '59,841 km'
PARENT: <p class="sc-iBYQkw ffCutd" id="">59,841 km</p>
PARENT CLASS: ['sc-iBYQkw', 'ffCutd']

TEXT: '66,791 km'
PARENT: <p class="sc-iBYQkw ffCutd" id="">66,791 km</p>
PARENT CLASS: ['sc-iBYQkw', 'ffCutd']

TEXT: '31,678 km'
PARENT: <p class="sc-iBYQkw ffCutd" id="">31,678 km</p>
PARENT CLASS: ['sc-iBYQkw', 'ffCutd']

TEXT: '53,163 km'
PARENT: <p class="sc-iBYQkw ffCutd" id="">53,163 km</p>
PARENT CLASS: ['sc-iBYQkw', 'ffCutd']

In [34]:
lakh_elements = soup_H.find_all(
    string=lambda x: x and "Lakh" in x
)

for x in lakh_elements:
    print("\nTEXT:", repr(x.strip()))
    print("PARENT:", x.parent)
    print("PARENT CLASS:", x.parent.get("class"))

TEXT: 'Under 5 Lakhs'
PARENT: <p class="sc-csuSiJ jJLDTq">Under 5 Lakhs</p>
PARENT CLASS: ['sc-csuSiJ', 'jJLDTq']

TEXT: 'Under 10 Lakhs'
PARENT: <p class="sc-csuSiJ jJLDTq">Under 10 Lakhs</p>
PARENT CLASS: ['sc-csuSiJ', 'jJLDTq']

TEXT: 'Under 15 Lakhs'
PARENT: <p class="sc-csuSiJ jJLDTq">Under 15 Lakhs</p>
PARENT CLASS: ['sc-csuSiJ', 'jJLDTq']

TEXT: 'Under 20 Lakhs'
PARENT: <p class="sc-csuSiJ jJLDTq">Under 20 Lakhs</p>
PARENT CLASS: ['sc-csuSiJ', 'jJLDTq']

TEXT: '1 Lakh+ Happy Drives stories'
PARENT: <h2 class="styles_heading___zdXI">1 Lakh+ Happy Drives stories</h2>
PARENT CLASS: ['styles_heading___zdXI']


In [35]:
for div in soup_H.find_all("div"):
    text = div.get_text(" | ", strip=True)

    if (
        "km" in text.lower()
        and "Petrol" in text
        and "Manual" in text
    ):
        print(text[:1000])
        print("CLASS:", div.get("class"))
        print("=" * 80)

All | Luxe | Budget | â‚¹ | 50,000 | â‚¹ | 75,00,000 | Minimum | Maximum | Make & Model | All Brands | NEXON | Swift | Kwid | Baleno | City | SELTOS | Maruti | ( | 577 | ) | Hyundai | ( | 379 | ) | Tata | ( | 265 | ) | Mahindra | ( | 145 | ) | Renault | ( | 135 | ) | Honda | ( | 133 | ) | Volkswagen | ( | 103 | ) | KIA | ( | 102 | ) | Ford | ( | 78 | ) | Skoda | ( | 78 | ) | MG | ( | 77 | ) | Toyota | ( | 68 | ) | Nissan | ( | 64 | ) | Datsun | ( | 17 | ) | BMW | ( | 16 | ) | Audi | ( | 16 | ) | Chevrolet | ( | 11 | ) | Jeep | ( | 9 | ) | CITROEN | ( | 9 | ) | Volvo | ( | 9 | ) | Mercedes Benz | ( | 8 | ) | Landrover | ( | 5 | ) | Fiat | ( | 5 | ) | Porsche | ( | 0 | ) | Mitsubishi | ( | 0 | ) | Lexus | ( | 0 | ) | Mini | ( | 0 | ) | Premier | ( | 0 | ) | BYD | ( | 0 | ) | Ssangyong | ( | 0 | ) | ISUZU | ( | 0 | ) | Force Motors | ( | 0 | ) | Jaguar | ( | 0 | ) | Car Category | Verified Direct Seller | ( | 1808 | ) | Sold by owners directly | Cars24 Owned Stock | ( | 501 | ) | Listed b
CLASS: ['styles_wrapper__kukeC']
================================================================================
All | Luxe | Budget | â‚¹ | 50,000 | â‚¹ | 75,00,000 | Minimum | Maximum | Make & Model | All Brands | NEXON | Swift | Kwid | Baleno | City | SELTOS | Maruti | ( | 577 | ) | Hyundai | ( | 379 | ) | Tata | ( | 265 | ) | Mahindra | ( | 145 | ) | Renault | ( | 135 | ) | Honda | ( | 133 | ) | Volkswagen | ( | 103 | ) | KIA | ( | 102 | ) | Ford | ( | 78 | ) | Skoda | ( | 78 | ) | MG | ( | 77 | ) | Toyota | ( | 68 | ) | Nissan | ( | 64 | ) | Datsun | ( | 17 | ) | BMW | ( | 16 | ) | Audi | ( | 16 | ) | Chevrolet | ( | 11 | ) | Jeep | ( | 9 | ) | CITROEN | ( | 9 | ) | Volvo | ( | 9 | ) | Mercedes Benz | ( | 8 | ) | Landrover | ( | 5 | ) | Fiat | ( | 5 | ) | Porsche | ( | 0 | ) | Mitsubishi | ( | 0 | ) | Lexus | ( | 0 | ) | Mini | ( | 0 | ) | Premier | ( | 0 | ) | BYD | ( | 0 | ) | Ssangyong | ( | 0 | ) | ISUZU | ( | 0 | ) | Force Motors | ( | 0 | ) | Jaguar | ( | 0 | ) | Car Category | Verified Direct Seller | ( | 1808 | ) | Sold by owners directly | Cars24 Owned Stock | ( | 501 | ) | Listed b
CLASS: ['container']
================================================================================
All | Luxe | Budget | â‚¹ | 50,000 | â‚¹ | 75,00,000 | Minimum | Maximum | Make & Model | All Brands | NEXON | Swift | Kwid | Baleno | City | SELTOS | Maruti | ( | 577 | ) | Hyundai | ( | 379 | ) | Tata | ( | 265 | ) | Mahindra | ( | 145 | ) | Renault | ( | 135 | ) | Honda | ( | 133 | ) | Volkswagen | ( | 103 | ) | KIA | ( | 102 | ) | Ford | ( | 78 | ) | Skoda | ( | 78 | ) | MG | ( | 77 | ) | Toyota | ( | 68 | ) | Nissan | ( | 64 | ) | Datsun | ( | 17 | ) | BMW | ( | 16 | ) | Audi | ( | 16 | ) | Chevrolet | ( | 11 | ) | Jeep | ( | 9 | ) | CITROEN | ( | 9 | ) | Volvo | ( | 9 | ) | Mercedes Benz | ( | 8 | ) | Landrover | ( | 5 | ) | Fiat | ( | 5 | ) | Porsche | ( | 0 | ) | Mitsubishi | ( | 0 | ) | Lexus | ( | 0 | ) | Mini | ( | 0 | ) | Premier | ( | 0 | ) | BYD | ( | 0 | ) | Ssangyong | ( | 0 | ) | ISUZU | ( | 0 | ) | Force Motors | ( | 0 | ) | Jaguar | ( | 0 | ) | Car Category | Verified Direct Seller | ( | 1808 | ) | Sold by owners directly | Cars24 Owned Stock | ( | 501 | ) | Listed b
CLASS: ['styles_listingContentWrapper__mvP_s']
================================================================================
Previous | Next | 2309 Second Hand Cars in Hyderabad | Best Match | Explore 2309 used cars in Hyderabad, the City of Pearls. Whether you are looking for a versatile SUV for a getaway to Ananthagiri Hills, a comfortable sedan to drive along Necklace Road, or a hatchback that can make its way through the busy streets of Charminar, no matter what your need is, our diverse inventory of used cars in Hyderabad has for every need. | Whether you are looking for a used car with a manual transmission, like 86% of buyers chose in 2024 (Cars24 internal data), or an automatic driving experience as preferred by 14% of used car buyers in 2024 (Cars24 internal data), our inventory of used | Manual | , | Automatic | cars in Hyderabad covers every preference, including fuel choices such as | Petrol | , | Diesel | , | CNG | , | Electric | and | Hybrid | . | Discover used cars from our pre-inspected inventory, alongside second hand cars from verified sellers, that come with easy financing options. Choose
CLASS: ['styles_carListingContainer__uob_6']
================================================================================
Cars24 Owned Stock | 2025 Maruti Swift | VXi | 28,750 km | Petrol | Manual | TG-07 | EMI â‚¹11,386/m* | â‚¹6.67L | â‚¹6.45 lakh | + other charges | Kompally, Hyderabad | Cars24 Owned Stock | 2021 Tata NEXON | XMA SUNROOF PETROL | 63,925 km | Petrol | Auto | TS-08 | EMI â‚¹10,027/m* | â‚¹5.91L | â‚¹5.68 lakh | + other charges | Kompally, Hyderabad | Cars24 Owned Stock | 2023 Tata NEXON | XM SUNROOF PETROL | 38,495 km | Petrol | Manual | TS-07 | EMI â‚¹12,516/m* | â‚¹7.37L | â‚¹7.09 lakh | + other charges | Bachupally, Hyderabad | Cars24 Owned Stock | 2020 KIA SELTOS | HTX 1.5 PETROL | 62,584 km | Petrol | Manual | TS-09 | EMI â‚¹13,766/m* | â‚¹8.40L | â‚¹7.80 lakh | + other charges | Kompally, Hyderabad | Cars24 Owned Stock | 2017 Maruti Alto 800 | VXI | 46,197 km | Petrol | Manual | AP-31 | EMI â‚¹4,497/m* | â‚¹2.48L | â‚¹2.30 lakh | + other charges | Kompally, Hyderabad | Cars24 Owned Stock | 2018 Tata Tiago | XM PETROL | 59,841 km | Petrol | Manual | TS-08 | EMI â‚¹5,865/m* | â‚¹3.64
CLASS: ['styles_wrapper__b4UUV']
================================================================================
Cars24 Owned Stock | 2025 Maruti Swift | VXi | 28,750 km | Petrol | Manual | TG-07 | EMI â‚¹11,386/m* | â‚¹6.67L | â‚¹6.45 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_normalCardWrapper__qDZjq']
================================================================================
Cars24 Owned Stock | 2025 Maruti Swift | VXi | 28,750 km | Petrol | Manual | TG-07 | EMI â‚¹11,386/m* | â‚¹6.67L | â‚¹6.45 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_contentWrap__9oSrl']
================================================================================
2025 Maruti Swift | VXi | 28,750 km | Petrol | Manual | TG-07 | EMI â‚¹11,386/m* | â‚¹6.67L | â‚¹6.45 lakh | + other charges
CLASS: ['styles_outer__NTVth']
================================================================================
2025 Maruti Swift | VXi | 28,750 km | Petrol | Manual | TG-07
CLASS: ['sc-ikHGeh', 'YJxbH']
================================================================================
28,750 km | Petrol | Manual | TG-07
CLASS: ['sc-kZLDfE', 'eiWwkw']
================================================================================
Cars24 Owned Stock | 2023 Tata NEXON | XM SUNROOF PETROL | 38,495 km | Petrol | Manual | TS-07 | EMI â‚¹12,516/m* | â‚¹7.37L | â‚¹7.09 lakh | + other charges | Bachupally, Hyderabad
CLASS: ['styles_normalCardWrapper__qDZjq']
================================================================================
Cars24 Owned Stock | 2023 Tata NEXON | XM SUNROOF PETROL | 38,495 km | Petrol | Manual | TS-07 | EMI â‚¹12,516/m* | â‚¹7.37L | â‚¹7.09 lakh | + other charges | Bachupally, Hyderabad
CLASS: ['styles_contentWrap__9oSrl']
================================================================================
2023 Tata NEXON | XM SUNROOF PETROL | 38,495 km | Petrol | Manual | TS-07 | EMI â‚¹12,516/m* | â‚¹7.37L | â‚¹7.09 lakh | + other charges
CLASS: ['styles_outer__NTVth']
================================================================================
2023 Tata NEXON | XM SUNROOF PETROL | 38,495 km | Petrol | Manual | TS-07
CLASS: ['sc-ikHGeh', 'YJxbH']
================================================================================
38,495 km | Petrol | Manual | TS-07
CLASS: ['sc-kZLDfE', 'eiWwkw']
================================================================================
Cars24 Owned Stock | 2020 KIA SELTOS | HTX 1.5 PETROL | 62,584 km | Petrol | Manual | TS-09 | EMI â‚¹13,766/m* | â‚¹8.40L | â‚¹7.80 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_normalCardWrapper__qDZjq']
================================================================================
Cars24 Owned Stock | 2020 KIA SELTOS | HTX 1.5 PETROL | 62,584 km | Petrol | Manual | TS-09 | EMI â‚¹13,766/m* | â‚¹8.40L | â‚¹7.80 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_contentWrap__9oSrl']
================================================================================
2020 KIA SELTOS | HTX 1.5 PETROL | 62,584 km | Petrol | Manual | TS-09 | EMI â‚¹13,766/m* | â‚¹8.40L | â‚¹7.80 lakh | + other charges
CLASS: ['styles_outer__NTVth']
================================================================================
2020 KIA SELTOS | HTX 1.5 PETROL | 62,584 km | Petrol | Manual | TS-09
CLASS: ['sc-ikHGeh', 'YJxbH']
================================================================================
62,584 km | Petrol | Manual | TS-09
CLASS: ['sc-kZLDfE', 'eiWwkw']
================================================================================
Cars24 Owned Stock | 2017 Maruti Alto 800 | VXI | 46,197 km | Petrol | Manual | AP-31 | EMI â‚¹4,497/m* | â‚¹2.48L | â‚¹2.30 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_normalCardWrapper__qDZjq']
================================================================================
Cars24 Owned Stock | 2017 Maruti Alto 800 | VXI | 46,197 km | Petrol | Manual | AP-31 | EMI â‚¹4,497/m* | â‚¹2.48L | â‚¹2.30 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_contentWrap__9oSrl']
================================================================================
2017 Maruti Alto 800 | VXI | 46,197 km | Petrol | Manual | AP-31 | EMI â‚¹4,497/m* | â‚¹2.48L | â‚¹2.30 lakh | + other charges
CLASS: ['styles_outer__NTVth']
================================================================================
2017 Maruti Alto 800 | VXI | 46,197 km | Petrol | Manual | AP-31
CLASS: ['sc-ikHGeh', 'YJxbH']
================================================================================
46,197 km | Petrol | Manual | AP-31
CLASS: ['sc-kZLDfE', 'eiWwkw']
================================================================================
Cars24 Owned Stock | 2018 Tata Tiago | XM PETROL | 59,841 km | Petrol | Manual | TS-08 | EMI â‚¹5,865/m* | â‚¹3.64L | â‚¹3.32 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_normalCardWrapper__qDZjq']
================================================================================
Cars24 Owned Stock | 2018 Tata Tiago | XM PETROL | 59,841 km | Petrol | Manual | TS-08 | EMI â‚¹5,865/m* | â‚¹3.64L | â‚¹3.32 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_contentWrap__9oSrl']
================================================================================
2018 Tata Tiago | XM PETROL | 59,841 km | Petrol | Manual | TS-08 | EMI â‚¹5,865/m* | â‚¹3.64L | â‚¹3.32 lakh | + other charges
CLASS: ['styles_outer__NTVth']
================================================================================
2018 Tata Tiago | XM PETROL | 59,841 km | Petrol | Manual | TS-08
CLASS: ['sc-ikHGeh', 'YJxbH']
================================================================================
59,841 km | Petrol | Manual | TS-08
CLASS: ['sc-kZLDfE', 'eiWwkw']
================================================================================
Cars24 Owned Stock | 2020 Renault Kwid | CLIMBER 1.0 (O) | 66,791 km | Petrol | Manual | TS-15 | EMI â‚¹5,366/m* | â‚¹3.04 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_normalCardWrapper__qDZjq']
================================================================================
Cars24 Owned Stock | 2020 Renault Kwid | CLIMBER 1.0 (O) | 66,791 km | Petrol | Manual | TS-15 | EMI â‚¹5,366/m* | â‚¹3.04 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_contentWrap__9oSrl']
================================================================================
2020 Renault Kwid | CLIMBER 1.0 (O) | 66,791 km | Petrol | Manual | TS-15 | EMI â‚¹5,366/m* | â‚¹3.04 lakh | + other charges
CLASS: ['styles_outer__NTVth']
================================================================================
2020 Renault Kwid | CLIMBER 1.0 (O) | 66,791 km | Petrol | Manual | TS-15
CLASS: ['sc-ikHGeh', 'YJxbH']
================================================================================
66,791 km | Petrol | Manual | TS-15
CLASS: ['sc-kZLDfE', 'eiWwkw']
================================================================================
Cars24 Owned Stock | 2021 Nissan MAGNITE | XV MT | 31,678 km | Petrol | Manual | TS-09 | EMI â‚¹9,169/m* | â‚¹5.33L | â‚¹5.19 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_normalCardWrapper__qDZjq']
================================================================================
Cars24 Owned Stock | 2021 Nissan MAGNITE | XV MT | 31,678 km | Petrol | Manual | TS-09 | EMI â‚¹9,169/m* | â‚¹5.33L | â‚¹5.19 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_contentWrap__9oSrl']
================================================================================
2021 Nissan MAGNITE | XV MT | 31,678 km | Petrol | Manual | TS-09 | EMI â‚¹9,169/m* | â‚¹5.33L | â‚¹5.19 lakh | + other charges
CLASS: ['styles_outer__NTVth']
================================================================================
2021 Nissan MAGNITE | XV MT | 31,678 km | Petrol | Manual | TS-09
CLASS: ['sc-ikHGeh', 'YJxbH']
================================================================================
31,678 km | Petrol | Manual | TS-09
CLASS: ['sc-kZLDfE', 'eiWwkw']
================================================================================
Cars24 Owned Stock | 2021 Maruti Baleno | ZETA PETROL 1.2 | 53,163 km | Petrol | Manual | TS-11 | EMI â‚¹9,621/m* | â‚¹5.65L | â‚¹5.45 lakh | + other charges | Upperpally, Attapur, Hyderabad
CLASS: ['styles_normalCardWrapper__qDZjq']
================================================================================
Cars24 Owned Stock | 2021 Maruti Baleno | ZETA PETROL 1.2 | 53,163 km | Petrol | Manual | TS-11 | EMI â‚¹9,621/m* | â‚¹5.65L | â‚¹5.45 lakh | + other charges | Upperpally, Attapur, Hyderabad
CLASS: ['styles_contentWrap__9oSrl']
================================================================================
2021 Maruti Baleno | ZETA PETROL 1.2 | 53,163 km | Petrol | Manual | TS-11 | EMI â‚¹9,621/m* | â‚¹5.65L | â‚¹5.45 lakh | + other charges
CLASS: ['styles_outer__NTVth']
================================================================================
2021 Maruti Baleno | ZETA PETROL 1.2 | 53,163 km | Petrol | Manual | TS-11
CLASS: ['sc-ikHGeh', 'YJxbH']
================================================================================
53,163 km | Petrol | Manual | TS-11
CLASS: ['sc-kZLDfE', 'eiWwkw']
================================================================================
Cars24 Owned Stock | 2018 Hyundai Creta | SX 1.6 Petrol | 83,407 km | Petrol | Manual | TS-08 | EMI â‚¹12,652/m* | â‚¹7.42L | â‚¹7.17 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_normalCardWrapper__qDZjq']
================================================================================
Cars24 Owned Stock | 2018 Hyundai Creta | SX 1.6 Petrol | 83,407 km | Petrol | Manual | TS-08 | EMI â‚¹12,652/m* | â‚¹7.42L | â‚¹7.17 lakh | + other charges | Kompally, Hyderabad
CLASS: ['styles_contentWrap__9oSrl']
================================================================================
2018 Hyundai Creta | SX 1.6 Petrol | 83,407 km | Petrol | Manual | TS-08 | EMI â‚¹12,652/m* | â‚¹7.42L | â‚¹7.17 lakh | + other charges
CLASS: ['styles_outer__NTVth']
================================================================================
2018 Hyundai Creta | SX 1.6 Petrol | 83,407 km | Petrol | Manual | TS-08
CLASS: ['sc-ikHGeh', 'YJxbH']
================================================================================
83,407 km | Petrol | Manual | TS-08
CLASS: ['sc-kZLDfE', 'eiWwkw']
================================================================================
Cars24 Owned Stock | 2019 Ford Ecosport | TITANIUM 1.5L THUNDER EDTION PETROL | 78,090 km | Petrol | Manual | TS-08 | EMI â‚¹11,477/m* | â‚¹6.84L | â‚¹6.50 lakh | + other charges | Bachupally, Hyderabad
CLASS: ['styles_normalCardWrapper__qDZjq']
================================================================================
Cars24 Owned Stock | 2019 Ford Ecosport | TITANIUM 1.5L THUNDER EDTION PETROL | 78,090 km | Petrol | Manual | TS-08 | EMI â‚¹11,477/m* | â‚¹6.84L | â‚¹6.50 lakh | + other charges | Bachupally, Hyderabad
CLASS: ['styles_contentWrap__9oSrl']
================================================================================
2019 Ford Ecosport | TITANIUM 1.5L THUNDER EDTION PETROL | 78,090 km | Petrol | Manual | TS-08 | EMI â‚¹11,477/m* | â‚¹6.84L | â‚¹6.50 lakh | + other charges
CLASS: ['styles_outer__NTVth']
================================================================================
2019 Ford Ecosport | TITANIUM 1.5L THUNDER EDTION PETROL | 78,090 km | Petrol | Manual | TS-08
CLASS: ['sc-ikHGeh', 'YJxbH']
================================================================================
78,090 km | Petrol | Manual | TS-08
CLASS: ['sc-kZLDfE', 'eiWwkw']
================================================================================
Cars24 Owned Stock | 2017 Maruti Alto K10 | VXI | 58,191 km | Petrol | Manual | TS-07 | EMI â‚¹4,767/m* | â‚¹2.69L | â‚¹2.44 lakh | + other charges | Bachupally, Hyderabad
CLASS: ['styles_normalCardWrapper__qDZjq']
================================================================================
Cars24 Owned Stock | 2017 Maruti Alto K10 | VXI | 58,191 km | Petrol | Manual | TS-07 | EMI â‚¹4,767/m* | â‚¹2.69L | â‚¹2.44 lakh | + other charges | Bachupally, Hyderabad
CLASS: ['styles_contentWrap__9oSrl']
================================================================================
2017 Maruti Alto K10 | VXI | 58,191 km | Petrol | Manual | TS-07 | EMI â‚¹4,767/m* | â‚¹2.69L | â‚¹2.44 lakh | + other charges
CLASS: ['styles_outer__NTVth']
================================================================================
2017 Maruti Alto K10 | VXI | 58,191 km | Petrol | Manual | TS-07
CLASS: ['sc-ikHGeh', 'YJxbH']
================================================================================
58,191 km | Petrol | Manual | TS-07
CLASS: ['sc-kZLDfE', 'eiWwkw']
================================================================================
Cars24 Owned Stock | 2019 KIA SELTOS | HTK 1.5 PETROL | 70,038 km | Petrol | Manual | TS-10 | EMI â‚¹11,665/m* | â‚¹8.66L | â‚¹6.61 lakh | + other charges | Upperpally, Attapur, Hyderabad
CLASS: ['styles_normalCardWrapper__qDZjq']
================================================================================
Cars24 Owned Stock | 2019 KIA SELTOS | HTK 1.5 PETROL | 70,038 km | Petrol | Manual | TS-10 | EMI â‚¹11,665/m* | â‚¹8.66L | â‚¹6.61 lakh | + other charges | Upperpally, Attapur, Hyderabad
CLASS: ['styles_contentWrap__9oSrl']
================================================================================
2019 KIA SELTOS | HTK 1.5 PETROL | 70,038 km | Petrol | Manual | TS-10 | EMI â‚¹11,665/m* | â‚¹8.66L | â‚¹6.61 lakh | + other charges
CLASS: ['styles_outer__NTVth']
================================================================================
2019 KIA SELTOS | HTK 1.5 PETROL | 70,038 km | Petrol | Manual | TS-10
CLASS: ['sc-ikHGeh', 'YJxbH']
================================================================================
70,038 km | Petrol | Manual | TS-10
CLASS: ['sc-kZLDfE', 'eiWwkw']
================================================================================
Cars24 Owned Stock | 2021 Honda Amaze | 1.2L I-VTEC VX | 58,544 km | Petrol | Manual | TS-08 | EMI â‚¹9,356/m* | â‚¹5.52L | â‚¹5.30 lakh | + other charges | Bachupally, Hyderabad
CLASS: ['styles_normalCardWrapper__qDZjq']
================================================================================

In [36]:
links = soup_H.find_all("a")

print("Total links:", len(links))

for link in links:
    text = link.get_text(" ", strip=True)

    if "km" in text.lower():
        print("\nTEXT:", text)
        print("HREF:", link.get("href"))
        print("CLASS:", link.get("class"))
        print("-" * 100)

Total links: 470

TEXT: Cars24 Owned Stock 2025 Maruti Swift VXi 28,750 km Petrol Manual TG-07 EMI â‚¹11,386/m* â‚¹6.67L â‚¹6.45 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-maruti-swift-2025-cars-hyderabad-10438776195/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2021 Tata NEXON XMA SUNROOF PETROL 63,925 km Petrol Auto TS-08 EMI â‚¹10,027/m* â‚¹5.91L â‚¹5.68 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-tata-nexon-2021-cars-hyderabad-12101594127/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2023 Tata NEXON XM SUNROOF PETROL 38,495 km Petrol Manual TS-07 EMI â‚¹12,516/m* â‚¹7.37L â‚¹7.09 lakh + other charges Bachupally, Hyderabad
HREF: https://www.cars24.com/buy-used-tata-nexon-2023-cars-hyderabad-10442798105/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2020 KIA SELTOS HTX 1.5 PETROL 62,584 km Petrol Manual TS-09 EMI â‚¹13,766/m* â‚¹8.40L â‚¹7.80 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-kia-seltos-2020-cars-hyderabad-10442294101/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2017 Maruti Alto 800 VXI 46,197 km Petrol Manual AP-31 EMI â‚¹4,497/m* â‚¹2.48L â‚¹2.30 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-maruti-alto-800-2017-cars-hyderabad-12259996104/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2018 Tata Tiago XM PETROL 59,841 km Petrol Manual TS-08 EMI â‚¹5,865/m* â‚¹3.64L â‚¹3.32 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-tata-tiago-2018-cars-hyderabad-10442892186/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2020 Renault Kwid CLIMBER 1.0 (O) 66,791 km Petrol Manual TS-15 EMI â‚¹5,366/m* â‚¹3.04 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-renault-kwid-2020-cars-hyderabad-10475097122/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2021 Nissan MAGNITE XV MT 31,678 km Petrol Manual TS-09 EMI â‚¹9,169/m* â‚¹5.33L â‚¹5.19 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-nissan-magnite-2021-cars-hyderabad-10413498129/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2021 Maruti Baleno ZETA PETROL 1.2 53,163 km Petrol Manual TS-11 EMI â‚¹9,621/m* â‚¹5.65L â‚¹5.45 lakh + other charges Upperpally, Attapur, Hyderabad
HREF: https://www.cars24.com/buy-used-maruti-baleno-2021-cars-hyderabad-10454691161/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2018 Hyundai Creta SX 1.6 Petrol 83,407 km Petrol Manual TS-08 EMI â‚¹12,652/m* â‚¹7.42L â‚¹7.17 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-hyundai-creta-2018-cars-hyderabad-10415194187/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2019 Ford Ecosport TITANIUM 1.5L THUNDER EDTION PETROL 78,090 km Petrol Manual TS-08 EMI â‚¹11,477/m* â‚¹6.84L â‚¹6.50 lakh + other charges Bachupally, Hyderabad
HREF: https://www.cars24.com/buy-used-ford-ecosport-2019-cars-hyderabad-10471198127/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2017 Maruti Alto K10 VXI 58,191 km Petrol Manual TS-07 EMI â‚¹4,767/m* â‚¹2.69L â‚¹2.44 lakh + other charges Bachupally, Hyderabad
HREF: https://www.cars24.com/buy-used-maruti-alto-k10-2017-cars-hyderabad-10476295132/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2019 KIA SELTOS HTK 1.5 PETROL 70,038 km Petrol Manual TS-10 EMI â‚¹11,665/m* â‚¹8.66L â‚¹6.61 lakh + other charges Upperpally, Attapur, Hyderabad
HREF: https://www.cars24.com/buy-used-kia-seltos-2019-cars-hyderabad-10014162705/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2021 Honda Amaze 1.2L I-VTEC VX 58,544 km Petrol Manual TS-08 EMI â‚¹9,356/m* â‚¹5.52L â‚¹5.30 lakh + other charges Bachupally, Hyderabad
HREF: https://www.cars24.com/buy-used-honda-amaze-2021-cars-hyderabad-10436594128/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2017 Volkswagen Polo GT TSI AT 57,634 km Petrol Auto TS-13 EMI â‚¹9,539/m* â‚¹5.70L â‚¹4.88 lakh + other charges Bachupally, Hyderabad
HREF: https://www.cars24.com/buy-used-volkswagen-polo-2017-cars-hyderabad-10459490116/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2015 Maruti Swift Dzire VXI 52,374 km Petrol Manual TS-09 EMI â‚¹8,711/m* â‚¹3.36L â‚¹3.31 lakh + other charges Upperpally, Attapur, Hyderabad
HREF: https://www.cars24.com/buy-used-maruti-swift-dzire-2015-cars-hyderabad-10417097105/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2018 Hyundai Verna 1.6 VTVT SX O 59,610 km Petrol Manual TS-07 EMI â‚¹12,445/m* â‚¹7.20L â‚¹7.05 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-hyundai-verna-2018-cars-hyderabad-10448290162/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2019 Hyundai Creta SX 1.6 PETROL 85,640 km Petrol Manual TS-08 EMI â‚¹11,533/m* â‚¹8.36L â‚¹6.53 lakh + other charges Uppal, Hyderabad
HREF: https://www.cars24.com/buy-used-hyundai-creta-2019-cars-hyderabad-10429497184/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2014 Maruti Swift Dzire VDI 1,50,064 km Diesel Manual AP-31 EMI â‚¹14,075/m* â‚¹3.20L â‚¹2.99 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-maruti-swift-dzire-2014-cars-hyderabad-12235591143/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

TEXT: Cars24 Owned Stock 2014 Mahindra XUV500 W8 99,805 km Diesel Manual TS-11 EMI â‚¹20,990/m* â‚¹4.60L â‚¹4.46 lakh + other charges Uppal, Hyderabad
HREF: https://www.cars24.com/buy-used-mahindra-xuv500-2014-cars-hyderabad-10461495183/
CLASS: ['styles_carCardWrapper__sXLIp']
----------------------------------------------------------------------------------------------------

In [37]:
for link in soup_H.find_all("a"):
    text = link.get_text(" ", strip=True)

    if any(x in text.lower() for x in ["km", "petrol", "diesel"]):
        print("\nTEXT:", text[:500])
        print("HREF:", link.get("href"))
        print("CLASS:", link.get("class"))
        print("=" * 100)

TEXT: Petrol
HREF: https://www.cars24.com/buy-used-petrol-cars-hyderabad/
CLASS: ['sc-bYMpWq', 'dWepEO']
====================================================================================================

TEXT: Diesel
HREF: https://www.cars24.com/buy-used-diesel-cars-hyderabad/
CLASS: ['sc-bYMpWq', 'dWepEO']
====================================================================================================

TEXT: Petrol
HREF: https://www.cars24.com/buy-used-petrol-cars-hyderabad/
CLASS: None
====================================================================================================

TEXT: Diesel
HREF: https://www.cars24.com/buy-used-diesel-cars-hyderabad/
CLASS: None
====================================================================================================

TEXT: Cars24 Owned Stock 2025 Maruti Swift VXi 28,750 km Petrol Manual TG-07 EMI â‚¹11,386/m* â‚¹6.67L â‚¹6.45 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-maruti-swift-2025-cars-hyderabad-10438776195/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2021 Tata NEXON XMA SUNROOF PETROL 63,925 km Petrol Auto TS-08 EMI â‚¹10,027/m* â‚¹5.91L â‚¹5.68 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-tata-nexon-2021-cars-hyderabad-12101594127/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2023 Tata NEXON XM SUNROOF PETROL 38,495 km Petrol Manual TS-07 EMI â‚¹12,516/m* â‚¹7.37L â‚¹7.09 lakh + other charges Bachupally, Hyderabad
HREF: https://www.cars24.com/buy-used-tata-nexon-2023-cars-hyderabad-10442798105/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2020 KIA SELTOS HTX 1.5 PETROL 62,584 km Petrol Manual TS-09 EMI â‚¹13,766/m* â‚¹8.40L â‚¹7.80 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-kia-seltos-2020-cars-hyderabad-10442294101/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2017 Maruti Alto 800 VXI 46,197 km Petrol Manual AP-31 EMI â‚¹4,497/m* â‚¹2.48L â‚¹2.30 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-maruti-alto-800-2017-cars-hyderabad-12259996104/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2018 Tata Tiago XM PETROL 59,841 km Petrol Manual TS-08 EMI â‚¹5,865/m* â‚¹3.64L â‚¹3.32 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-tata-tiago-2018-cars-hyderabad-10442892186/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2020 Renault Kwid CLIMBER 1.0 (O) 66,791 km Petrol Manual TS-15 EMI â‚¹5,366/m* â‚¹3.04 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-renault-kwid-2020-cars-hyderabad-10475097122/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2021 Nissan MAGNITE XV MT 31,678 km Petrol Manual TS-09 EMI â‚¹9,169/m* â‚¹5.33L â‚¹5.19 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-nissan-magnite-2021-cars-hyderabad-10413498129/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2021 Maruti Baleno ZETA PETROL 1.2 53,163 km Petrol Manual TS-11 EMI â‚¹9,621/m* â‚¹5.65L â‚¹5.45 lakh + other charges Upperpally, Attapur, Hyderabad
HREF: https://www.cars24.com/buy-used-maruti-baleno-2021-cars-hyderabad-10454691161/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2018 Hyundai Creta SX 1.6 Petrol 83,407 km Petrol Manual TS-08 EMI â‚¹12,652/m* â‚¹7.42L â‚¹7.17 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-hyundai-creta-2018-cars-hyderabad-10415194187/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2019 Ford Ecosport TITANIUM 1.5L THUNDER EDTION PETROL 78,090 km Petrol Manual TS-08 EMI â‚¹11,477/m* â‚¹6.84L â‚¹6.50 lakh + other charges Bachupally, Hyderabad
HREF: https://www.cars24.com/buy-used-ford-ecosport-2019-cars-hyderabad-10471198127/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2017 Maruti Alto K10 VXI 58,191 km Petrol Manual TS-07 EMI â‚¹4,767/m* â‚¹2.69L â‚¹2.44 lakh + other charges Bachupally, Hyderabad
HREF: https://www.cars24.com/buy-used-maruti-alto-k10-2017-cars-hyderabad-10476295132/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2019 KIA SELTOS HTK 1.5 PETROL 70,038 km Petrol Manual TS-10 EMI â‚¹11,665/m* â‚¹8.66L â‚¹6.61 lakh + other charges Upperpally, Attapur, Hyderabad
HREF: https://www.cars24.com/buy-used-kia-seltos-2019-cars-hyderabad-10014162705/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2021 Honda Amaze 1.2L I-VTEC VX 58,544 km Petrol Manual TS-08 EMI â‚¹9,356/m* â‚¹5.52L â‚¹5.30 lakh + other charges Bachupally, Hyderabad
HREF: https://www.cars24.com/buy-used-honda-amaze-2021-cars-hyderabad-10436594128/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2017 Volkswagen Polo GT TSI AT 57,634 km Petrol Auto TS-13 EMI â‚¹9,539/m* â‚¹5.70L â‚¹4.88 lakh + other charges Bachupally, Hyderabad
HREF: https://www.cars24.com/buy-used-volkswagen-polo-2017-cars-hyderabad-10459490116/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2015 Maruti Swift Dzire VXI 52,374 km Petrol Manual TS-09 EMI â‚¹8,711/m* â‚¹3.36L â‚¹3.31 lakh + other charges Upperpally, Attapur, Hyderabad
HREF: https://www.cars24.com/buy-used-maruti-swift-dzire-2015-cars-hyderabad-10417097105/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2018 Hyundai Verna 1.6 VTVT SX O 59,610 km Petrol Manual TS-07 EMI â‚¹12,445/m* â‚¹7.20L â‚¹7.05 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-hyundai-verna-2018-cars-hyderabad-10448290162/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2019 Hyundai Creta SX 1.6 PETROL 85,640 km Petrol Manual TS-08 EMI â‚¹11,533/m* â‚¹8.36L â‚¹6.53 lakh + other charges Uppal, Hyderabad
HREF: https://www.cars24.com/buy-used-hyundai-creta-2019-cars-hyderabad-10429497184/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2014 Maruti Swift Dzire VDI 1,50,064 km Diesel Manual AP-31 EMI â‚¹14,075/m* â‚¹3.20L â‚¹2.99 lakh + other charges Kompally, Hyderabad
HREF: https://www.cars24.com/buy-used-maruti-swift-dzire-2014-cars-hyderabad-12235591143/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

TEXT: Cars24 Owned Stock 2014 Mahindra XUV500 W8 99,805 km Diesel Manual TS-11 EMI â‚¹20,990/m* â‚¹4.60L â‚¹4.46 lakh + other charges Uppal, Hyderabad
HREF: https://www.cars24.com/buy-used-mahindra-xuv500-2014-cars-hyderabad-10461495183/
CLASS: ['styles_carCardWrapper__sXLIp']
====================================================================================================

In [38]:
car_cards = soup_H.find_all(
    "a",
    class_="styles_carCardWrapper__sXLIp"
)

print("Number of cars:", len(car_cards))

Number of cars: 20

In [39]:
print(car_cards[0].prettify()[:5000])

<a class="styles_carCardWrapper__sXLIp" href="https://www.cars24.com/buy-used-maruti-swift-2025-cars-hyderabad-10438776195/" target="_blank">
 <div class="styles_normalCardWrapper__qDZjq">
  <div class="sc-EJAjd hNsDMY">
   <div class="sc-jGNhvR fqybIt">
    <div class="sc-bQmOxs kJWcCf">
     <img alt="2025 Maruti Swift - Hatchback - Petrol - Manual - â‚¹6.45 lakh" class="shrinkOnTouch" data-nimg="1" decoding="async" height="120" loading="lazy" src="https://media.cars24.com/hello-ar/dev/transformed/uploads/no_bg/e4a6d034-8844-11f1-bd59-02ede2007fbe/84382ade-db9b-4b87-88b6-6e80f65d03a5/91985817-16e9-493c-8942-d6761b15c39f/d39a8e60-deca-4da4-af35-a47cd91d44e0/slot/1.png?w=200&amp;format=auto&amp;dpr=2&amp;pad=48,0,0,0&amp;trim-color=auto" style="color:transparent" width="220"/>
    </div>
    <div class="sc-fWQKxQ dpElzZ">
     <div class="styles_outer__ZH1Cg">
      <button>
       <img alt="Add to wishlist" class="styles_icon__vn_BC shrinkOnTouch" data-nimg="1" decoding="async" height="24" loading="lazy" src="https://assets.cars24.com/production/india-website/catalog/260727175840/_next/static/media/icon-heart-empty.479d2b8c.svg" style="color:transparent" width="24"/>
      </button>
     </div>
    </div>
   </div>
  </div>
  <div class="styles_contentWrap__9oSrl">
   <div class="styles_newBadgeContainer__hBIWA" style="background-color:#FFFFFF">
    <div class="styles_badgeContent__J3Wnd">
     <img alt="Cars24 owned stock" data-nimg="1" decoding="async" height="14" loading="lazy" src="https://static-cdn.cars24.com/prod/cms/2025/12/26/c875199d-a85f-4350-b5a8-81cffe722da4Frame%202147233492.png" style="color:transparent" width="14"/>
     <span class="sc-iBYQkw iUzhPv" id="">
      Cars24 Owned Stock
     </span>
     <svg fill="none" height="25" style="position:absolute;right:2px;top:0px;transform:translateX(100%)" viewbox="0 0 28 19" width="38" xmlns="http://www.w3.org/2000/svg">
      <path d="M0.375 0H0.568182C6.20394 0 11.2869 3.88867 13.4545 9.09091C15.8286 14.7886 21.3957 19 27.5682 19H0.375V0Z" fill="white">
      </path>
     </svg>
    </div>
   </div>
   <div class="styles_outer__NTVth">
    <div class="sc-ikHGeh YJxbH">
     <div class="sc-hAQmFh bYESmV">
      <div class="sc-bhNKFj jqscHP">
       <span class="sc-iBYQkw oBPOd" id="">
        2025 Maruti Swift
       </span>
       <span class="sc-iBYQkw gZCACi" id="">
        <!-- -->
        VXi
       </span>
      </div>
     </div>
     <div class="sc-kZLDfE eiWwkw">
      <ul class="sc-uhnfI jFODEm">
       <div class="sc-ftTHYN dEVcfe">
        <p class="sc-iBYQkw ffCutd" id="">
         28,750 km
        </p>
       </div>
       <div class="sc-ftTHYN dEVcfe">
        <p class="sc-iBYQkw ffCutd" id="">
         Petrol
        </p>
       </div>
       <div class="sc-ftTHYN dEVcfe">
        <p class="sc-iBYQkw ffCutd" id="">
         Manual
        </p>
       </div>
       <div class="sc-ftTHYN dEVcfe">
        <p class="sc-iBYQkw ffCutd" id="">
         TG-07
        </p>
       </div>
      </ul>
     </div>
    </div>
    <div class="sc-eDZJfb htopvE">
     <div class="styles_pricingDetail__Q_3hz">
      <div class="styles_flexItem__2z__J">
       <span class="sc-pyfCh ffpspm">
        <p>
         EMI â‚¹11,386/m*
        </p>
       </span>
      </div>
      <div class="styles_flexItem__2z__J">
       <div class="styles_priceWrap__VwWBV">
        <p class="sc-iBYQkw Vkhwc" id="">
         â‚¹6.67L
        </p>
        <p class="sc-iBYQkw frMukX" id="">
         â‚¹6.45 lakh
        </p>
       </div>
       <div class="styles_labelContainer__NIr_r">
        <span class="sc-pyfCh kXYCPQ">
         <p>
          + other charges
         </p>
        </span>
       </div>
      </div>
     </div>
    </div>
   </div>
   <div class="sc-dubCtS kynEqW">
    <div class="styles_hubAddress__URioy">
     <img alt="address-icon" data-nimg="1" decoding="async" height="12" loading="lazy" src="https://media.cars24.com/india/car-catalog/icons_13122024/location.png" style="color:transparent" width="12"/>
     <div class="styles_ellipsis__uatjG">
      <p class="sc-iBYQkw gZCACi" id="">
       Kompally, Hyderabad
      </p>
     </div>
    </div>
   </div>
  </div>
 </div>
</a>